[tool.poetry]
name = "your_project_name"
version = "0.1.0"
description = "A simple Python project with many packages"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10.16"
requests = "^2.25"
numpy = "^1.21"
pandas = "^1.3"
flask = "^2.0"
matplotlib = "^3.4"
sqlalchemy = "^1.4"
scikit-learn = "^0.24"
pytest = "^6.2"  # You could remove this from here if it's meant to be a dev dependency
beautifulsoup4 = "^4.10"
pillow = "^8.4"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake8 = "^3.9"
mypy = "^0.9"
pre-commit = "^2.0"
tox = "^3.24"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
