name: Playwright Tests

on:
  workflow_dispatch:  # Adding manual trigger option
    inputs:
      branch:
        description: 'Branch to run the tests on'
        required: false
        default: 'main'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}  # Use branch from input or default to current ref

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate  # Activating the virtual environment
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run your tests and generate Allure report
      run: |
        source venv/bin/activate  # Ensure the virtual environment is active
        cd Tests
        pytest --alluredir=allure-results -vs || true  # Generate Allure results in the specified directory
        chmod -R 777 allure-results  # Ensure appropriate permissions on allure-results directory

    - name: List contents of allure-results
      run: ls -R Tests/allure-results  # Verify that the allure-results directory exists and contains files

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: Tests/allure-results  # Upload the Allure results as an artifact
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false
