name: Testing Vishnu

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch (or any other branch)

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          # Define IMAGE_TAG using the current commit SHA or tag
          IMAGE_TAG="my-repo/my-image:${GITHUB_SHA}"
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .

      - name: Push Docker image to registry
        run: |
          # Ensure IMAGE_TAG is not empty before pushing
          if [ -z "$IMAGE_TAG" ]; then
            echo "ERROR: IMAGE_TAG is empty. Cannot push the Docker image."
            exit 1
          fi
          
          # Print the tag we're pushing
          echo "Pushing Docker image: $IMAGE_TAG"
          
          # Push the Docker image to the registry (no login required for public Docker registry)
          docker push $IMAGE_TAG

      # Set image_tag as an environment variable to use in subsequent jobs
      - name: Set image_tag output
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "The image tag has been set as an environment variable for future steps."
