name: Playwright Tests in Docker

on:
#   schedule:
#     - cron: '*/2 * * * *'
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Branch to run on the cluster'
        required: false
        default: 'Mira'
      test_component:
        description: 'The directory where tests are located'
        required: false
        default: 'Notifications'  
      marker:
        description: 'The pytest marker to filter tests (e.g., "smoke")'
        required: false
        default: 'Regression'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}  # Use branch from input or default to current ref

    - name: Set up Docker
      run: |
        docker build -t playwright-test .  # Build the Docker image using the Dockerfile in the repo

    - name: Run tests in Docker container
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace playwright-test bash -c "
          python -m venv venv && \
          source venv/bin/activate && \
          python -m pip install --upgrade pip && \
          pip install poetry && \
          poetry install && \
          cd ${GITHUB_EVENT_INPUTS_TEST_DIRECTORY} && \
          if [ -z \"${INPUT_MARKER}\" ]; then \
            pytest --alluredir=allure-results -vs || true; \
          else \
            pytest -m \"${INPUT_MARKER}\" --alluredir=allure-results -vs || true; \
          fi && \
          chmod -R 777 allure-results
        "

    
    - name: List contents of allure-results
      run: docker run --rm -v $PWD:/workspace -w /workspace playwright-test ls -R ${GITHUB_EVENT_INPUTS_TEST_DIRECTORY}/allure-results  # Verify that the allure-results directory exists and contains files

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: ${GITHUB_EVENT_INPUTS_TEST_DIRECTORY}/allure-results  # Upload the Allure results as an artifact
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false
