on:
  repository_dispatch:
    types: [generic-event]  # Listen for the event type specified in the trigger workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python (or your environment)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Use your desired version of Python (or adjust for Node.js, etc.)

      - name: Install dependencies
        run: |
          # Install specific Python dependencies
          pip install poetry
          poetry install 
          
      - name: Check if Dockerfile exists and build Docker image
        run: |
          # Check if Dockerfile exists in the root or in a subdirectory (e.g., 'docker/Dockerfile')
          if [ -f Dockerfile ]; then
            DOCKERFILE_PATH="Dockerfile"
          else
            echo "Error: Dockerfile not found!" && exit 1
          fi

          # Build the Docker image using the found Dockerfile path
          docker build -f $DOCKERFILE_PATH -t ${{ github.sha }}:latest .
          
          # Optionally, save the image as a tar file if needed
          docker save "sha": "${{ github.sha }}":latest -o, "sha": "${{ github.sha }}".tar

      - name: Get the commit SHA
        run: |
          echo "SHA: ${{ github.event.client_payload.sha }}"
