on:
  repository_dispatch:
    types: [generic-event]  # Listen for the event type specified in the trigger workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python (or your environment) and install dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Use your desired version of Python (or adjust for Node.js, etc.)

      - name: Install dependencies
        run: |
          # For example, installing Python dependencies using pip
          pip install numpy pandas requests matplotlib flask scikit-learn sqlalchemy
  # Adjust for your dependencies or package manager (npm install for Node.js, etc.)

      - name: Build Docker image with dependencies (without Docker login)
        run: |
          # Make sure Docker is installed on the runner
          sudo apt-get update
          sudo apt-get install -y docker.io
          
          # Build Docker image and tag it
          docker build -t your-image-name:${{ github.sha }} .  # Build image and tag with the commit SHA
          
          # Optionally, you can save the image as a tar file if you want to use it locally
          docker save your-image-name:${{ github.sha }} -o your-image-name-${{ github.sha }}.tar

      - name: Get the commit SHA
        run: |
          echo "SHA: ${{ github.event.client_payload.sha }}"
