name: Build and Push Docker Image Without Login

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Build Docker image
      run: |
        docker build -t vishnu4reddy/my-public-image:latest .

    - name: Push Docker image
      run: |
        docker push vishnu4reddy/my-public-image:latest
