name: Playwright Tests in Docker

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: True
        options:
          - mira
          - polaris
          - pavo
          - hoku
          
      test_component:
        description: 'Components to run tests with'
        required: True
        default: 'all'
        type: choice
        options:
          - acct_mgmt
          - authz
          - notifications
          - support_assistent
          - ups
          - unified
          - sam
          - all
          
      marker:
        description: 'The pytest marker to filter tests (e.g., "smoke")'
        required: True
        default: 'all'
        type: choice
        options:
          - all
          - Regression
          - Plv

jobs:
  pull_and_test:
    runs-on: ubuntu-latest
    needs: testing_vishnu  # Ensures the 'testing_vishnu' workflow ran successfully
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the latest Docker image from 'testing_vishnu' workflow
      - name: Set Docker image and environment variables
        run: |
          IMAGE_TAG="${{ needs.testing_vishnu.outputs.image_tag }}"
          echo "Retrieved image tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          # Set marker
          echo "Running tests with marker: ${{ github.event.inputs.marker }}"
          echo "TEST_MARKER='${{ github.event.inputs.marker }}'" >> $GITHUB_ENV

          # Set environment
          echo "Running tests in environment: ${{ github.event.inputs.environment }}"
          echo "ENVIRONMENT='${{ github.event.inputs.environment }}'" >> $GITHUB_ENV

      - name: Pull the latest Docker image
        run: |
          docker pull $IMAGE_TAG

  # Matrix job to run tests in parallel for each component
  test_components:
    runs-on: ubuntu-latest
    needs: pull_and_test  # Ensures the 'pull_and_test' job has finished
    strategy:
      matrix:
        component: ${{ fromJson(needs.pull_and_test.outputs.test_components) }}  # Parse components from output

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set environment variables and run tests for the specific component
      - name: Set environment variable for the test component
        run: |
          component=${{ matrix.component }}
          echo "Running tests for component: $component"
          echo "TEST_COMPONENT=$component" >> $GITHUB_ENV
          echo "TEST_MARKER=${{ env.TEST_MARKER }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ env.ENVIRONMENT }}" >> $GITHUB_ENV

      - name: Run tests for component
        run: |
          pytest_path="./tests/${{ matrix.component }}/"
          if [[ -d "$pytest_path" ]]; then
            echo "Running pytest on ${pytest_path} with marker ${env.TEST_MARKER} in environment ${env.ENVIRONMENT}"
            docker run -e TEST_COMPONENT="${{ matrix.component }}" -e TEST_MARKER="${{ env.TEST_MARKER }}" -e ENVIRONMENT="${{ env.ENVIRONMENT }}" $IMAGE_TAG python -m pytest $pytest_path -m "${{ env.TEST_MARKER }}" --env "${{ env.ENVIRONMENT }}"
          else
            echo "No tests found for component $component in ${pytest_path}"
          fi
