name: Playwright Tests in Docker

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: True
        options:
          - mira
          - polaris
          - pavo
          - hoku
      test_component:
        description: 'Components to run tests with'
        required: True
        default: 'all'
        type: choice
        options:
          - acct_mgmt
          - authz
          - notifications
          - support_assistent
          - ups
          - unified
          - sam
          - all
      marker:
        description: 'The pytest marker to filter tests (e.g., "smoke")'
        required: True
        default: 'all'
        type: choice
        options:
          - all
          - Regression
          - Plv

jobs:
  pull_and_test:
    runs-on: ubuntu-latest
    needs: testing_vishnu  # Ensures the 'testing_vishnu' workflow ran successfully
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the latest Docker image from 'testing_vishnu' workflow
      - name: Set Docker image and environment variables
        run: |
          IMAGE_TAG="${{ needs.testing_vishnu.outputs.image_tag }}"
          echo "Retrieved image tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          # Set marker
          echo "Running tests with marker: ${{ github.event.inputs.marker }}"
          echo "TEST_MARKER='${{ github.event.inputs.marker }}'" >> $GITHUB_ENV

          # Set environment
          echo "Running tests in environment: ${{ github.event.inputs.environment }}"
          echo "ENVIRONMENT='${{ github.event.inputs.environment }}'" >> $GITHUB_ENV

      - name: Pull the latest Docker image
        run: |
          docker pull $IMAGE_TAG  # Pull the Docker image using the tag from the previous step
          echo "Pulled Docker image: $IMAGE_TAG"
