name: Playwright Tests

on:
  workflow_dispatch:  # Adding manual trigger option
    inputs:
      branch:
        description: 'Branch to run the tests on'
        required: false
        default: 'main'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}  # Use branch from input or default to current ref
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name:  install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate  # Activating the virtual environment
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run your tests
      run: |
        source venv/bin/activate  # Ensure the virtual environment is active
        pytest --tracing=retain-on-failure
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: Tests
